name: flutter_swiper_view
description: The best swiper(carousel) for flutter, with multiple layouts, infinite loop. Compatible with Android & iOS.
version: 1.0.0
homepage: https://github.com/whevether/flutter_swiper_view

dependencies:
  flutter:
    sdk: flutter


environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
